config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  get 'main/index'

  resources :books do
    member do
      get :delete
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    validates :price, presence: true
    validates :published_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @count = Book.count
    @book = Book.new(id: @count + 1)
    flash.notice= "Book was successfully created"
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    flash.notice = "Book was successfully edited"
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    # respond_to do |format|
    #   if @book.save
    #     format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
    #     format.json { render :show, status: :created, location: @book }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @book.errors, status: :unprocessable_entity }
    #   end
    # end

    if @book.save
      redirect_to books_path, notice: "Book created"
    else
      render('new')
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    # respond_to do |format|
    #   if @book.update(book_params)
    #     format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
    #     format.json { render :show, status: :ok, location: @book }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @book.errors, status: :unprocessable_entity }
    #   end
    # end

    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else 
      render('edit')
    end
    flash[:notice]= "Book was successfully updated"
  end

  def delete
    @book = Book.find(params[:id])
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    flash[:notice]= "Book was successfully destroyed"

    # respond_to do |format|
    #   format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(
        :title,
        :author,
        :price,
        :published_date
        )
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        # render('index')
    end

    def about
        @created_by = "Maria"
        @id = params['id']
        @page = params[:page]
        # render('about')
    end

    def hello
        redirect_to(action: 'index')
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

</div>

app/views/books/_form.html.erb
<table summary="Book form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
  <tr>
    <th>Author</th>
    <td><%= f.text_field(:author) %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.number_field(:price) %></td>
  </tr>
  <tr>
    <th>Published Date</th>
    <td><%= f.select :published_date, ['9/19/1967', '10/2/1980', '6/21/2002'] %></td>
  </tr>
</table>

app/views/books/delete.html.erb
<%= link_to("Back to list", books_path, class: 'back-link') %>

<div class="books delete">
    <h2>Delete book</h2>

    <%= form_for(@book, method: 'delete') do |f| %>
    <% # url: book_path(@book), method: 'delete' %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
        <%= f.submit("Delete book") %>
    </div>

    <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Edit book</h2>

  <%= form_for(@book) do |f| %>
  <% # url: book_path(@book), method: 'patch' %>

  <%= render(partial: 'form', locals: {f: f}) %>

  <div class="form-buttons">
    <%= f.submit("Edit book") %>
  </div>

  <% end %>
</div>

app/views/books/index.html.erb
<header>
    <div class="title"><strong>Book Collection</strong></div>
</header>

<% flash.each do |name, msg| %>
  <ul>
      <li><%= msg %></li>
  </ul>
<% end %>

<div id="text" class="books index">
    <h2>Books</h2>

    <%= link_to("Add New Book", new_book_path, class: 'action new') %>

    <table class="listing" summary="Book list" style="width: 100%;">
        <tr class="header">
        <th>Title</th>
        <th>Author</th>
        <th>Price</th>
        <th>Published Date</th>
        <th>Actions</th>
        </tr>
    <% @books.each do |book| %>
    <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.price %></td>
        <td><%= book.published_date %></td>
        <td class="actions">
        <%= link_to("Show", book_path(book), class: 'action show') %>
        <%= link_to("Edit", edit_book_path(book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), class: 'action delete') %>
        </td>
    </tr>

    <% end %>
    </table>
</div>

app/views/books/new.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books new">
    <h2>Create Book</h2>

    <%= form_for(@book) do |f| %>
    <% # url: books_path, method: 'post' %>
    <%= render(partial: 'form', locals: {f: f}) %>
    <div class="form-buttons">
        <%= f.submit("Create Book") %>
    </div>
    <% end %>
</div>

app/views/books/show.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books show">
    <h2>Show book</h2>

    <div class="actions">
        <%= link_to('Edit', edit_book_path(@book)) %>
        <%= link_to('Delete', delete_book_path(@book)) %>
    </div>

    <table summary="Book detail view">
        <tr>
            <th>Title</th>
            <td><%= @book.title %></td>
        </tr>
        <tr>
            <th>Author</th>
            <td><%= @book.author %></td>
        </tr>
        <tr>
            <th>Price</th>
            <td><%= @book.price %></td>
        </tr>
        <tr>
            <th>Published Date</th>
            <td><%= @book.published_date %></td>
        </tr>
        <tr>
            <th>Created</th>
            <td><%= @book.created_at %></td>
        </tr>
        <tr>
            <th>Updated</th>
            <td><%= @book.updated_at %></td>
        </tr>
    </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<header>
    <div class="title"><strong>Book Collection</strong></div>
</header>